version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "Actions"
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "Composer"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "npm"
