<?php
/**
 * Title: EINTRIKOT datenschutz
 * Slug: eintrikot/mvp-datenschutz
 * Categories: eintrikot
 */
?>
<!-- wp:group {"tagName":"section","className":"section page-intro","layout":{"type":"default"}} --><section class="wp-block-group section page-intro"><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Datenschutz.</h1><!-- /wp:heading --></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","className":"section legal-content","layout":{"type":"default"}} --><section class="wp-block-group section legal-content"><!-- wp:paragraph --><p>Der Schutz Ihrer personenbezogenen Daten ist uns wichtig. EINTRIKOT e.V. verarbeitet personenbezogene Daten ausschließlich nach den gesetzlichen Vorgaben, insbesondere der Datenschutz-Grundverordnung (DSGVO), dem Bundesdatenschutzgesetz (BDSG) und dem Telekommunikation-Digitale-Dienste-Datenschutz-Gesetz (TDDDG).</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Diese Datenschutzerklärung erläutert, welche Daten wir verarbeiten, wenn Sie unsere Website www.eintrikot.de besuchen, Mitglied bei uns werden, die EINTRIKOT-App (unseren geschützten Mitgliederbereich auf www.eintrikot.de) nutzen oder auf anderem Weg mit uns in Kontakt treten.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">1. Verantwortlicher</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><strong>EINTRIKOT e.V.</strong><br>Bachstr. 20<br>63452 Hanau<br>E-Mail: <a href="mailto:info@eintrikot.de">info@eintrikot.de</a></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Der Verein wird durch den Vorstand gemäß § 9 der Satzung vertreten. Für alle Fragen zum Datenschutz und zur Ausübung Ihrer Rechte erreichen Sie uns unter info@eintrikot.de.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">2. Überblick</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Personenbezogene Daten sind alle Informationen, die sich auf eine bestimmte oder bestimmbare Person beziehen, zum Beispiel Name, E-Mail-Adresse, Geburtsdatum oder Bankverbindung. Wir setzen folgende Systeme ein:</p><!-- /wp:paragraph -->
<!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li><strong>Website und EINTRIKOT-App</strong> auf www.eintrikot.de, betrieben mit WordPress bei der STRATO GmbH in Deutschland (Ziffern 3 bis 8).</li><!-- /wp:list-item --><!-- wp:list-item --><li><strong>WISO MeinVerein</strong> der Buhl Data Service GmbH für Mitgliedsantrag, Mitgliederverwaltung und Beitragseinzug (Ziffer 4).</li><!-- /wp:list-item --><!-- wp:list-item --><li><strong>Google Workspace</strong> für unsere E-Mails mit Adressen @eintrikot.de und gegebenenfalls Online-Meetings (Ziffern 9 und 12).</li><!-- /wp:list-item --></ul><!-- /wp:list -->
<!-- wp:paragraph --><p>Wir setzen keine Werbe-, Analyse- oder Tracking-Dienste ein, binden keine Inhalte externer Anbieter ein und laden auch Schriftarten ausschließlich von unserem eigenen Server.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">3. Besuch der Website</h2><!-- /wp:heading -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">3.1 Hosting und Server-Protokolle</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Unsere Website wird von der STRATO GmbH, Otto-Ostrowski-Straße 7, 10249 Berlin, auf Servern in Deutschland betrieben. Mit STRATO besteht ein Vertrag zur Auftragsverarbeitung nach Art. 28 DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Beim Aufruf unserer Seiten verarbeitet der Server technisch notwendige Daten: IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, übertragene Datenmenge, Browser und Betriebssystem sowie die zuvor besuchte Seite (Referrer). Diese Daten sind erforderlich, um die Website auszuliefern und ihre Sicherheit zu gewährleisten, etwa zur Abwehr von Angriffen. Rechtsgrundlage ist unser berechtigtes Interesse nach Art. 6 Abs. 1 lit. f DSGVO. Die Protokolle werden nach einer kurzen, vom Hoster festgelegten Frist gelöscht und nicht mit anderen Daten zusammengeführt.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">3.2 Cookies</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wir verwenden ausschließlich technisch notwendige Cookies. Einen Cookie-Banner zeigen wir deshalb nicht an. Die Cookies werden nur gesetzt, wenn Sie sich in der EINTRIKOT-App anmelden:</p><!-- /wp:paragraph -->
<!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li><strong>wordpress_test_cookie</strong>: prüft, ob Ihr Browser Cookies zulässt; Dauer: Sitzung.</li><!-- /wp:list-item --><!-- wp:list-item --><li><strong>wordpress_logged_in_…</strong> und <strong>wordpress_sec_…</strong>: halten Sie angemeldet. Ohne „Angemeldet bleiben“ gelten sie bis zum Schließen des Browsers. Mit „Angemeldet bleiben“ gelten sie 90 Tage, für Konten von Vorstand, Redaktion und Administration 14 Tage.</li><!-- /wp:list-item --></ul><!-- /wp:list -->
<!-- wp:paragraph --><p>Rechtsgrundlage ist § 25 Abs. 2 Nr. 2 TDDDG in Verbindung mit Art. 6 Abs. 1 lit. b DSGVO. Über „Abmelden“ und unter Service → Konto („Auf allen anderen Geräten abmelden“) beenden Sie Ihre Anmeldung jederzeit.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">3.3 Schutz der Anmeldung</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Um das Erraten von Passwörtern zu verhindern, zählen wir fehlgeschlagene Anmeldeversuche. Dafür speichern wir für 15 Minuten einen nicht umkehrbaren Prüfwert (Hash) aus eingegebener E-Mail-Adresse und IP-Adresse; nach fünf Fehlversuchen ist die Anmeldung für diese Zeit gesperrt. Anfragen zum Zurücksetzen des Passworts begrenzen wir auf drei pro Stunde und Konto. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (Schutz der Konten unserer Mitglieder).</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">3.4 Anonyme Zählung auf „Mitglied werden“</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Vor dem Mitgliedsantrag erklärt ein Hinweisfenster den Ablauf. Wir zählen monatlich, wie oft dieses Fenster geöffnet und wie oft „weiter zum Antrag“ gewählt wird. Dafür setzen wir keine Cookies. Damit wiederholte Klicks nur einmal zählen, speichern wir höchstens eine Stunde lang einen nicht umkehrbaren Prüfwert (Hash), der aus der IP-Adresse gebildet wird; dauerhaft bleiben nur die Monatssummen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (Verbesserung unseres Aufnahmeverfahrens).</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">4. Mitglied werden und Mitgliederverwaltung (WISO MeinVerein)</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Für den Mitgliedsantrag, die Mitgliederverwaltung und den Beitragseinzug nutzen wir WISO MeinVerein Web der Buhl Data Service GmbH, Am Siebertsweiher 3/5, 57290 Neunkirchen („Buhl“). Mit Buhl besteht ein Vertrag zur Auftragsverarbeitung nach Art. 28 DSGVO; die Daten werden nach Angaben des Anbieters auf Servern in Deutschland gespeichert.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">4.1 Digitaler Mitgliedsantrag</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Über „Jetzt Mitglied werden“ gelangen Sie zum digitalen Mitgliedsantrag bei MeinVerein. Pflichtangaben sind Vor- und Nachname, E-Mail-Adresse und Geburtsdatum. Das Geburtsdatum benötigen wir, weil die Mitgliedschaft bis einschließlich 31 Jahre beitragsfrei ist und bei Minderjährigen die Zustimmung der Eltern erforderlich ist. Zahlen Sie per Lastschrift oder möchten Sie spenden, kommen Bankverbindung und SEPA-Lastschriftmandat hinzu.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Anbahnung und Durchführung der Mitgliedschaft).</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">4.2 Beiträge und Spenden</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Bei Lastschrift verarbeiten wir Kontoinhaber, IBAN, Mandatsreferenz und Mandatsdatum, bei Zahlung per Rechnung Ihre Kontaktdaten für die Zahlungsaufforderung. Für Spenden verarbeiten wir Betrag, Zahlungsweg und die für eine Zuwendungsbestätigung erforderlichen Angaben. Bankdaten verarbeiten wir ausschließlich in MeinVerein, nie in der EINTRIKOT-App. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO und für steuerliche Aufbewahrungspflichten Art. 6 Abs. 1 lit. c DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">5. EINTRIKOT-App (Mitgliederbereich)</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Die EINTRIKOT-App ist unser geschützter Mitgliederbereich auf www.eintrikot.de. Er ist nur nach Anmeldung zugänglich und wird von Suchmaschinen nicht erfasst. Geschützte Seiten werden nicht zwischengespeichert.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.1 Zugang</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Nach der Aufnahme übernehmen wir aus MeinVerein genau sechs Angaben in die App: Vor- und Nachname, E-Mail-Adresse, Mitgliedsnummer, Eintrittsdatum und Geburtsdatum. Die dafür verwendete Exportdatei wird nicht gespeichert. Sie erhalten eine Begrüßungs-E-Mail mit einem persönlichen Link, der 14 Tage und nur einmal gültig ist, und legen Ihr Passwort selbst fest. Wir versenden niemals Passwörter und fragen nie danach; gespeichert wird Ihr Passwort nur verschlüsselt (als Hashwert).</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>„Passwort vergessen?“ schickt einen Link, der 24 Stunden und nur einmal gültig ist. Nach einer Passwortänderung beenden wir alle Anmeldungen und informieren Sie per E-Mail. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.2 Mitgliedsurkunde</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Aus Name, Mitgliedsnummer und Eintrittsdatum erstellen wir Ihre Mitgliedsurkunde als PDF. Sie erhalten sie mit der Begrüßung und können sie jederzeit in der App herunterladen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.3 Profil und Sichtbarkeit</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Im Profil können Sie freiwillig weitere Angaben machen, zum Beispiel Wohnort und Region, aktuellen Verein, Team, Altersklasse, Trikotphase, Länderspiele und Stationen im Nationalteam (DHB-Vita), Beruf, Ausbildung, Hobbys, Mentoring-Angebote und -Wünsche, Links zu sozialen Netzwerken sowie ein Profilbild.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Sie entscheiden je Abschnitt mit einem Schalter, ob andere Mitglieder die Angaben sehen. Ausgeschaltet sieht sie nur die Vereinsverwaltung (Vorstand und Administration). Name und Profilbild sehen alle angemeldeten Mitglieder. Ihr Geburtsdatum bleibt immer privat; Ihr Alter und Ihren Geburtstag in den Vereinsinfos zeigen wir nur, wenn Sie das jeweils ausdrücklich einschalten. Profilbilder werden geschützt gespeichert und sind nicht öffentlich abrufbar. Außerhalb der App ist nichts davon sichtbar.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Rechtsgrundlage für die Kontodaten ist Art. 6 Abs. 1 lit. b DSGVO, für freiwillige Angaben und deren Freigabe Ihre Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO. Sie können Angaben jederzeit selbst ändern, löschen oder wieder verbergen.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.4 Links zu sozialen Netzwerken</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Im Profil können Sie freiwillig Links zu Ihren Profilen bei LinkedIn, Facebook und Instagram hinterlegen. Andere Mitglieder sehen sie – wenn Sie den Abschnitt „Social Media“ freigeben – als Logo des jeweiligen Netzwerks. Es handelt sich um einfache Links: Wir binden keine Inhalte oder Plugins der Netzwerke ein, und beim Aufruf eines Profils in der EINTRIKOT-App werden keine Daten an die Netzwerke übertragen. Erst wenn jemand auf ein Logo klickt, öffnet sich die Seite des Netzwerks; dort gelten dessen Datenschutzbestimmungen. Anbieter sind die LinkedIn Ireland Unlimited Company sowie für Facebook und Instagram die Meta Platforms Ireland Limited, beide mit Sitz in Dublin, Irland. Rechtsgrundlage ist Ihre Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO; Sie können die Links jederzeit entfernen.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.5 Mitgliederverzeichnis und Kennzahlen</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Im Mitgliederverzeichnis finden angemeldete Mitglieder einander. Suche und Filter berücksichtigen nur Angaben, die Sie freigegeben haben. Auf der öffentlichen Website zeigen wir Vereinskennzahlen, darunter die Summe der Länderspiele unserer Mitglieder. Sie wird nur aus freigegebenen Angaben gebildet und lässt keinen Rückschluss auf einzelne Personen zu. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (Vernetzung und Darstellung des Vereins) bzw. Ihre Freigabe.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.6 Service-Anfragen</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Über den Bereich „Service“ können Sie Anfragen an den Verein stellen, zum Beispiel zu geänderten Stammdaten, zum freiwilligen Förderbeitrag, zu Events oder zur Mitarbeit. Wir speichern Ihre Angaben mit Vorgangsnummer und Bearbeitungsstand; bearbeitet werden sie von Vorstand und Administration. Verbindliche Änderungen übernehmen wir von Hand in MeinVerein. Bankdaten erfragen wir hier nicht. Abgeschlossene Anfragen löschen wir 24 Monate nach der letzten Bearbeitung. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.7 Änderungsprotokoll</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Änderungen an Profilen, Anfragen und Konten protokollieren wir mit Zeitpunkt, bearbeitender Person und Anlass, damit Korrekturen der Vereinsverwaltung nachvollziehbar sind. Beim Geburtsdatum wird nur vermerkt, dass es geändert wurde. Das Protokoll ist nur für Vorstand und Administration einsehbar; Einträge werden nach 24 Monaten automatisch gelöscht. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (Nachvollziehbarkeit und Datensicherheit).</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5.8 Ende der Mitgliedschaft</h3><!-- /wp:heading -->
<!-- wp:paragraph --><p>Endet Ihre Mitgliedschaft, löschen wir Ihr Konto in der EINTRIKOT-App mit allen Profilangaben. Daten in MeinVerein bewahren wir nur so lange auf, wie gesetzliche Pflichten dies verlangen (Ziffer 14).</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">6. Minderjährige Mitglieder</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Mitglieder unter 18 Jahren benötigen für den Beitritt die Zustimmung ihrer Eltern. Nach dem Antrag bitten wir das junge Mitglied, die E-Mail-Adresse eines Elternteils einzutragen. Der Elternteil erhält eine E-Mail mit Informationen zum Verein und bestätigt auf einer Seite der EINTRIKOT-App die Zustimmung. Erst danach erhält das Mitglied seinen Zugang. Als Nachweis speichern wir Name und E-Mail-Adresse des Elternteils, den Zeitpunkt und den bestätigten Wortlaut; diese Angaben löschen wir drei Jahre nach dem 18. Geburtstag des Mitglieds.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Solange ein Mitglied minderjährig ist, sehen andere Mitglieder höchstens Name, Team, Altersklasse und Region, kein Alter, keinen Wohnort und keine weiteren Angaben. Im Mitgliederverzeichnis erscheint es nur, wenn die Eltern dem zugestimmt haben. Ab dem 18. Geburtstag entscheidet das Mitglied selbst.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO (Mitgliedschaft mit Zustimmung der gesetzlichen Vertreter) und Art. 6 Abs. 1 lit. f DSGVO (Nachweis der Zustimmung). Eine Zustimmung kann jederzeit per E-Mail an info@eintrikot.de widerrufen werden.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">7. Vereinsinformationen und Newsletter</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Als Mitglied erhalten Sie E-Mails, die zur Mitgliedschaft gehören, etwa Zugangs- und Sicherheitsinformationen, Rückmeldungen zu Ihren Anfragen und Einladungen zur Mitgliederversammlung (§ 8 Abs. 4 der Satzung). Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Unseren Newsletter mit Neuigkeiten aus dem Netzwerk erhalten Sie nur, wenn die Einstellung „EINTRIKOT-Newsletter erhalten“ in Ihrem Profil eingeschaltet ist. Sie können sie jederzeit ausschalten; jede Ausgabe enthält außerdem einen Abmeldelink. Rechtsgrundlage ist Ihre Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">8. Kontakt</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wenn Sie uns per E-Mail schreiben, verarbeiten wir Ihre Angaben, um Ihre Anfrage zu beantworten. Rechtsgrundlage ist je nach Anliegen Art. 6 Abs. 1 lit. b oder lit. f DSGVO. Wir löschen die Nachrichten, wenn die Anfrage erledigt ist und keine Aufbewahrungspflichten bestehen.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">9. E-Mail-Versand über Google Workspace</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Unsere E-Mails mit Adressen @eintrikot.de, auch die automatischen E-Mails der EINTRIKOT-App, versenden und empfangen wir über Google Workspace der Google Cloud EMEA Limited, 70 Sir John Rogerson’s Quay, Dublin 2, Irland. Mit Google besteht ein Vertrag zur Auftragsverarbeitung nach Art. 28 DSGVO. Verarbeitet werden Absender, Empfänger, Inhalte und technische Verbindungsdaten der E-Mails.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Unsere E-Mails enthalten keine Zählpixel und keine nachgeladenen Bilder; das Logo ist direkt in die E-Mail eingebettet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b bzw. lit. f DSGVO (sichere und zuverlässige Kommunikation).</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">10. Spenden</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wenn Sie uns eine Spende zukommen lassen, verarbeiten wir Spendenhöhe, Zahlungsweg und die für die Zuwendungsbestätigung erforderlichen Kontaktdaten. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und lit. c DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">11. Veranstaltungen, Fotos und Videos</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Für die Organisation von Veranstaltungen verarbeiten wir die Angaben Ihrer Anmeldung (Art. 6 Abs. 1 lit. b DSGVO). Fotos und Videos, auf denen Sie erkennbar sind, veröffentlichen wir nur mit Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO), die Sie jederzeit mit Wirkung für die Zukunft widerrufen können.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">12. Online-Meetings mit Google Meet</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Für Online-Meetings und digitale Mitgliederversammlungen nutzen wir gegebenenfalls Google Meet als Teil von Google Workspace (Anbieter siehe Ziffer 9). Verarbeitet werden können Name, E-Mail-Adresse, Meeting-Daten (Titel, Zeitpunkt, Dauer, Teilnehmende), technische Daten sowie Audio-, Video- und Chat-Inhalte. Aufzeichnungen erfolgen nur nach vorheriger Ankündigung und, soweit erforderlich, mit Ihrer Einwilligung. Rechtsgrundlage ist je nach Anlass Art. 6 Abs. 1 lit. b, lit. f oder lit. a DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">13. Empfänger und Übermittlung in Drittländer</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wir geben personenbezogene Daten nur weiter, wenn dies zur Erfüllung unserer Aufgaben erforderlich ist, eine gesetzliche Pflicht besteht oder Sie eingewilligt haben. Als Auftragsverarbeiter nach Art. 28 DSGVO setzen wir ein:</p><!-- /wp:paragraph -->
<!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li><strong>STRATO GmbH</strong>, Berlin: Hosting von Website und EINTRIKOT-App</li><!-- /wp:list-item --><!-- wp:list-item --><li><strong>Buhl Data Service GmbH</strong>, Neunkirchen: WISO MeinVerein (Mitgliedsantrag, Mitgliederverwaltung, Beiträge)</li><!-- /wp:list-item --><!-- wp:list-item --><li><strong>Google Cloud EMEA Limited</strong>, Dublin: Google Workspace (E-Mail, gegebenenfalls Google Meet)</li><!-- /wp:list-item --></ul><!-- /wp:list -->
<!-- wp:paragraph --><p>Darüber hinaus erhalten Banken die für den Beitragseinzug erforderlichen Daten und das Finanzamt die gesetzlich vorgeschriebenen Angaben.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Bei Google Workspace ist eine Verarbeitung in den USA nicht ausgeschlossen. Google LLC ist nach dem EU-US Data Privacy Framework zertifiziert, für das ein Angemessenheitsbeschluss der EU-Kommission besteht (Art. 45 DSGVO); zusätzlich hat Google EU-Standardvertragsklauseln vereinbart (Art. 46 DSGVO). Website, EINTRIKOT-App und MeinVerein werden in Deutschland betrieben.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">14. Speicherdauer</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wir speichern personenbezogene Daten nur so lange, wie es für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen:</p><!-- /wp:paragraph -->
<!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li>Konto und Profil in der EINTRIKOT-App: bis zum Ende der Mitgliedschaft</li><!-- /wp:list-item --><!-- wp:list-item --><li>Service-Anfragen: 24 Monate nach der letzten Bearbeitung</li><!-- /wp:list-item --><!-- wp:list-item --><li>Änderungsprotokoll: 24 Monate</li><!-- /wp:list-item --><!-- wp:list-item --><li>Nachweis der Zustimmung der Eltern: bis drei Jahre nach dem 18. Geburtstag</li><!-- /wp:list-item --><!-- wp:list-item --><li>Zähldaten „Mitglied werden“: Verbindungswert höchstens eine Stunde, danach nur Monatssummen</li><!-- /wp:list-item --><!-- wp:list-item --><li>Mitgliederdaten in MeinVerein: bis zum Ende der Mitgliedschaft; Unterlagen zu Beiträgen und Spenden entsprechend den steuerlichen Aufbewahrungsfristen von in der Regel sechs bzw. zehn Jahren</li><!-- /wp:list-item --></ul><!-- /wp:list -->
<!-- wp:heading --><h2 class="wp-block-heading">15. Datensicherheit</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wir schützen Ihre Daten durch technische und organisatorische Maßnahmen: verschlüsselte Übertragung (HTTPS), Passwörter nur als Hashwert, einmalige und befristete Links statt versendeter Passwörter, Schutz vor dem Erraten von Passwörtern, Zugriffsrechte nach Rollen, Protokollierung von Änderungen und nicht öffentlich abrufbare Profilbilder.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">16. Ihre Rechte</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Sie haben das Recht auf:</p><!-- /wp:paragraph -->
<!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li>Auskunft über Ihre bei uns gespeicherten Daten (Art. 15 DSGVO)</li><!-- /wp:list-item --><!-- wp:list-item --><li>Berichtigung unrichtiger Daten (Art. 16 DSGVO)</li><!-- /wp:list-item --><!-- wp:list-item --><li>Löschung, soweit keine Aufbewahrungspflichten entgegenstehen (Art. 17 DSGVO)</li><!-- /wp:list-item --><!-- wp:list-item --><li>Einschränkung der Verarbeitung (Art. 18 DSGVO)</li><!-- /wp:list-item --><!-- wp:list-item --><li>Datenübertragbarkeit (Art. 20 DSGVO)</li><!-- /wp:list-item --><!-- wp:list-item --><li>Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen (Art. 21 DSGVO)</li><!-- /wp:list-item --><!-- wp:list-item --><li>Widerruf erteilter Einwilligungen mit Wirkung für die Zukunft (Art. 7 Abs. 3 DSGVO)</li><!-- /wp:list-item --></ul><!-- /wp:list -->
<!-- wp:paragraph --><p>Viele Angaben können Sie in der EINTRIKOT-App selbst ändern oder löschen. Für alle weiteren Anliegen schreiben Sie uns an info@eintrikot.de.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p>Sie können sich außerdem bei einer Datenschutzaufsichtsbehörde beschweren. Für uns zuständig ist der Hessische Beauftragte für Datenschutz und Informationsfreiheit, Postfach 3163, 65021 Wiesbaden, datenschutz.hessen.de.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">17. Keine automatisierten Entscheidungen</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wir treffen keine automatisierten Einzelentscheidungen im Sinne von Art. 22 DSGVO.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">18. Änderungen</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Wir passen diese Datenschutzerklärung an, wenn sich rechtliche Vorgaben, unsere Abläufe oder die eingesetzte Technik ändern. Es gilt die jeweils auf www.eintrikot.de veröffentlichte Fassung.</p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p><em>Stand: September 2026</em></p><!-- /wp:paragraph --></section><!-- /wp:group -->
